/**
 * A message on a request.
 *
 * Comments are the conversation half of a request; the history is the record of
 * what happened to it. They are kept apart deliberately: history entries are
 * generated by the system and visible to everyone who can see the request, while
 * a comment is written by a person and may be internal.
 *
 * There is no `editedAt` and no delete: a thread people can rewrite is not a
 * record of what was actually said, and the record is the point.
 */
export interface RequestComment {
  id: string;
  requestId: string;
  authorId: string;
  body: string;
  /**
   * Visible only to the assignee and managers — the handlers of the request.
   * Lets them note "third time this month, escalating" without the requester
   * reading it.
   */
  isInternal: boolean;
  at: Date;
}

/** A comment on its way into storage, before it has an id. */
export interface NewComment {
  authorId: string;
  body: string;
  isInternal: boolean;
  at: Date;
}
